In [1]:
#The jupyter notebook can be downloaded using the link at top right corner of the kaggle webpage if not fully rendered in the webpage. 

import numpy as np
import gensim
import os
import re

from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from gensim import corpora

from gensim.models.ldamulticore import LdaMulticore

import pandas as pd

In [2]:
!pip install scispacy

Collecting scispacy
  Downloading scispacy-0.2.4.tar.gz (38 kB)
Requirement already satisfied: spacy>=2.2.1 in /opt/conda/lib/python3.6/site-packages (from scispacy) (2.2.3)
Collecting awscli
  Downloading awscli-1.18.26-py2.py3-none-any.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 7.1 MB/s
Requirement already satisfied: conllu in /opt/conda/lib/python3.6/site-packages (from scispacy) (1.3.1)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from scispacy) (1.18.1)
Requirement already satisfied: joblib in /opt/conda/lib/python3.6/site-packages (from scispacy) (0.14.1)
Collecting nmslib>=1.7.3.6
  Downloading nmslib-2.0.5-cp36-cp36m-manylinux2010_x86_64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 27.4 MB/s
Requirement already satisfied: scikit-learn>=0.20.3 in /opt/conda/lib/python3.6/site-packages (from scispacy) (0.22.2.post1)
Collecting pysbd
  Downloading pysbd-0.2.3-py3-none-any.whl (24 kB)
Requirement already satisfied: srsly<1.1.0,>=0.1.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (1.0.2)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (0.4.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (3.0.2)
Requirement already satisfied: thinc<7.4.0,>=7.3.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (7.3.1)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (2.0.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (45.2.0.post20200210)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (1.0.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (2.22.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (1.0.2)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (0.6.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->scispacy) (0.9.6)
Requirement already satisfied: colorama<0.4.4,>=0.2.5; python_version != "3.4" in /opt/conda/lib/python3.6/site-packages (from awscli->scispacy) (0.4.3)
Collecting botocore==1.15.26
  Downloading botocore-1.15.26-py2.py3-none-any.whl (6.0 MB)
     |████████████████████████████████| 6.0 MB 31.9 MB/s
Requirement already satisfied: PyYAML<5.4,>=3.10; python_version != "3.4" in /opt/conda/lib/python3.6/site-packages (from awscli->scispacy) (5.3)
Collecting rsa<=3.5.0,>=3.1.2
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 3.2 MB/s
Requirement already satisfied: docutils<0.16,>=0.10 in /opt/conda/lib/python3.6/site-packages (from awscli->scispacy) (0.15.2)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.6/site-packages (from awscli->scispacy) (0.3.3)
Requirement already satisfied: pybind11>=2.2.3 in /opt/conda/lib/python3.6/site-packages (from nmslib>=1.7.3.6->scispacy) (2.4.3)
Requirement already satisfied: psutil in /opt/conda/lib/python3.6/site-packages (from nmslib>=1.7.3.6->scispacy) (5.6.7)
Requirement already satisfied: scipy>=0.17.0 in /opt/conda/lib/python3.6/site-packages (from scikit-learn>=0.20.3->scispacy) (1.4.1)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /opt/conda/lib/python3.6/site-packages (from thinc<7.4.0,>=7.3.0->spacy>=2.2.1->scispacy) (4.42.0)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /opt/conda/lib/python3.6/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.1->scispacy) (1.5.0)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->scispacy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->scispacy) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->scispacy) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->scispacy) (3.0.4)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from botocore==1.15.26->awscli->scispacy) (0.9.5)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.6/site-packages (from botocore==1.15.26->awscli->scispacy) (2.8.0)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/conda/lib/python3.6/site-packages (from rsa<=3.5.0,>=3.1.2->awscli->scispacy) (0.4.8)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.6/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.1->scispacy) (2.2.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.15.26->awscli->scispacy) (1.14.0)
Building wheels for collected packages: scispacy
  Building wheel for scispacy (setup.py) ... - \ done
  Created wheel for scispacy: filename=scispacy-0.2.4-py3-none-any.whl size=35203 sha256=8534cf31bc96020c2d3b4c559bd0c9ea283983a5c151c6a7c6922cc0784e94a7
  Stored in directory: /root/.cache/pip/wheels/80/01/69/37a2ab4f9b61773c187d83257ffb31365a5ad57e7779ae5e92
Successfully built scispacy
ERROR: allennlp 0.9.0 has requirement spacy<2.2,>=2.1.0, but you'll have spacy 2.2.3 which is incompatible.
Installing collected packages: botocore, rsa, awscli, nmslib, pysbd, scispacy
  Attempting uninstall: botocore
    Found existing installation: botocore 1.15.13
    Uninstalling botocore-1.15.13:
      Successfully uninstalled botocore-1.15.13
  Attempting uninstall: rsa
    Found existing installation: rsa 4.0
    Uninstalling rsa-4.0:
      Successfully uninstalled rsa-4.0
Successfully installed awscli-1.18.26 botocore-1.15.26 nmslib-2.0.5 pysbd-0.2.3 rsa-3.4.2 scispacy-0.2.4

In [3]:
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_md-0.2.4.tar.gz

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_md-0.2.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_md-0.2.4.tar.gz (70.0 MB)
     |████████████████████████████████| 70.0 MB 48 kB/s
Requirement already satisfied: spacy>=2.2.1 in /opt/conda/lib/python3.6/site-packages (from en-core-sci-md==0.2.4) (2.2.3)
Requirement already satisfied: numpy>=1.15.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (1.18.1)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (1.0.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (0.9.6)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (1.0.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (2.0.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (3.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (2.22.0)
Requirement already satisfied: thinc<7.4.0,>=7.3.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (7.3.1)
Requirement already satisfied: srsly<1.1.0,>=0.1.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (1.0.2)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (0.4.1)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (0.6.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.6/site-packages (from spacy>=2.2.1->en-core-sci-md==0.2.4) (45.2.0.post20200210)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /opt/conda/lib/python3.6/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.1->en-core-sci-md==0.2.4) (1.5.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->en-core-sci-md==0.2.4) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->en-core-sci-md==0.2.4) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->en-core-sci-md==0.2.4) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.1->en-core-sci-md==0.2.4) (2.8)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /opt/conda/lib/python3.6/site-packages (from thinc<7.4.0,>=7.3.0->spacy>=2.2.1->en-core-sci-md==0.2.4) (4.42.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.6/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.1->en-core-sci-md==0.2.4) (2.2.0)
Building wheels for collected packages: en-core-sci-md
  Building wheel for en-core-sci-md (setup.py) ... - \ | / - \ | / - \ | / done
  Created wheel for en-core-sci-md: filename=en_core_sci_md-0.2.4-py3-none-any.whl size=70498245 sha256=6f792a8a18637df595e4bf42a693ea7f734327792730f990617c87b1a8a11c64
  Stored in directory: /root/.cache/pip/wheels/0b/d7/91/ad4d42842bdd001ccd505e492eba644c4c97b1fc5558c1d5ee
Successfully built en-core-sci-md
Installing collected packages: en-core-sci-md
Successfully installed en-core-sci-md-0.2.4

In [4]:
#df = pd.read_csv('metadata.csv')
bucket = 'coviddata'
file = 'metadata.csv'
gcs_url = 'https://%(bucket)s.storage.googleapis.com/%(file)s' % {'bucket':bucket, 'file':file}
df = pd.read_csv(gcs_url)

In [5]:
df.head()

,sha,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,Microsoft Academic Paper ID,WHO #Covidence,has_full_text,full_text_file
0,NaN,Elsevier,Intrauterine virus infections and congenital h...,10.1016/0002-8703(72)90077-4,NaN,4361535.0,els-covid,Abstract The etiologic basis for the vast majo...,1972-12-31,"Overall, James C.",American Heart Journal,NaN,NaN,False,custom_license
1,NaN,Elsevier,Coronaviruses in Balkan nephritis,10.1016/0002-8703(80)90355-5,NaN,6243850.0,els-covid,NaN,1980-03-31,"Georgescu, Leonida; Diosi, Peter; Buţiu, Ioan;...",American Heart Journal,NaN,NaN,False,custom_license
2,NaN,Elsevier,Cigarette smoking and coronary heart disease: ...,10.1016/0002-8703(80)90356-7,NaN,7355701.0,els-covid,NaN,1980-03-31,"Friedman, Gary D",American Heart Journal,NaN,NaN,False,custom_license
3,aecbc613ebdab36753235197ffb4f35734b5ca63,Elsevier,Clinical and immunologic studies in identical ...,10.1016/0002-9343(73)90176-9,NaN,4579077.0,els-covid,"Abstract Middle-aged female identical twins, o...",1973-08-31,"Brunner, Carolyn M.; Horwitz, David A.; Shann,...",The American Journal of Medicine,NaN,NaN,True,custom_license
4,NaN,Elsevier,Epidemiology of community-acquired respiratory...,10.1016/0002-9343(85)90361-4,NaN,4014285.0,els-covid,Abstract Upper respiratory tract infections ar...,1985-06-28,"Garibaldi, Richard A.",The American Journal of Medicine,NaN,NaN,False,custom_license

In [6]:
df2 = df.drop(columns = ['sha', 'source_x', 'pmcid', 'license', 'Microsoft Academic Paper ID', 'WHO #Covidence', 'has_full_text'])

In [7]:
df2.head()

,title,doi,pubmed_id,abstract,publish_time,authors,journal,full_text_file
0,Intrauterine virus infections and congenital h...,10.1016/0002-8703(72)90077-4,4361535.0,Abstract The etiologic basis for the vast majo...,1972-12-31,"Overall, James C.",American Heart Journal,custom_license
1,Coronaviruses in Balkan nephritis,10.1016/0002-8703(80)90355-5,6243850.0,NaN,1980-03-31,"Georgescu, Leonida; Diosi, Peter; Buţiu, Ioan;...",American Heart Journal,custom_license
2,Cigarette smoking and coronary heart disease: ...,10.1016/0002-8703(80)90356-7,7355701.0,NaN,1980-03-31,"Friedman, Gary D",American Heart Journal,custom_license
3,Clinical and immunologic studies in identical ...,10.1016/0002-9343(73)90176-9,4579077.0,"Abstract Middle-aged female identical twins, o...",1973-08-31,"Brunner, Carolyn M.; Horwitz, David A.; Shann,...",The American Journal of Medicine,custom_license
4,Epidemiology of community-acquired respiratory...,10.1016/0002-9343(85)90361-4,4014285.0,Abstract Upper respiratory tract infections ar...,1985-06-28,"Garibaldi, Richard A.",The American Journal of Medicine,custom_license

In [8]:
df2.shape

(44220, 8)

In [9]:
df3 = df2.dropna(subset=['abstract'])

In [10]:
df3.shape

(35806, 8)

In [11]:
df3.head()

,title,doi,pubmed_id,abstract,publish_time,authors,journal,full_text_file
0,Intrauterine virus infections and congenital h...,10.1016/0002-8703(72)90077-4,4361535.0,Abstract The etiologic basis for the vast majo...,1972-12-31,"Overall, James C.",American Heart Journal,custom_license
3,Clinical and immunologic studies in identical ...,10.1016/0002-9343(73)90176-9,4579077.0,"Abstract Middle-aged female identical twins, o...",1973-08-31,"Brunner, Carolyn M.; Horwitz, David A.; Shann,...",The American Journal of Medicine,custom_license
4,Epidemiology of community-acquired respiratory...,10.1016/0002-9343(85)90361-4,4014285.0,Abstract Upper respiratory tract infections ar...,1985-06-28,"Garibaldi, Richard A.",The American Journal of Medicine,custom_license
5,Infectious diarrhea: Pathogenesis and risk fac...,10.1016/0002-9343(85)90367-5,2861742.0,Abstract Our understanding of the pathogenesis...,1985-06-28,"Cantey, J.Robert",The American Journal of Medicine,custom_license
6,New perspectives on the pathogenesis of rheuma...,10.1016/0002-9343(88)90356-7,3052052.0,Abstract In the pathogenesis of rheumatoid art...,1988-10-14,"Zvaifler, Nathan J.",The American Journal of Medicine,custom_license

In [12]:
import en_core_sci_md
nlp = en_core_sci_md.load(disable=["tagger", "parser", "ner"])
nlp.max_length = 2000000

In [13]:
import spacy

In [14]:
from spacy.tokenizer import Tokenizer

In [15]:
def tokenize(doc):
    
    return [token.text for token in nlp(doc) if not token.is_stop and not token.is_punct and not token.pos == 'PRON']

In [16]:
data = df3['abstract'].apply(tokenize)

In [17]:
data

0        [Abstract, etiologic, basis, vast, majority, c...
3        [Abstract, Middle-aged, female, identical, twi...
4        [Abstract, Upper, respiratory, tract, infectio...
5        [Abstract, understanding, pathogenesis, infect...
6        [Abstract, pathogenesis, rheumatoid, arthritis...
                               ...
44215    [study, aimed, identify, broad, spectrum, resp...
44216    [Abstract, enter, cells, enveloped, viruses, u...
44217    [Human, parainfluenza, viruses, cause, large, ...
44218    [Abstract, arenaviruses, chiefly, Lassa, virus...
44219    [vigorous, alloimmunity, allograft, usually, r...
Name: abstract, Length: 35806, dtype: object

In [18]:
vect = [nlp(doc).vector for doc in df3['abstract']]

In [19]:
from sklearn.neighbors import NearestNeighbors

In [20]:
nn = NearestNeighbors(n_neighbors=25, algorithm='ball_tree')
nn.fit(vect)

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                 radius=1.0)

In [21]:
query = "chloroquine hydroxycholoroquine HCoV-19 SARS-CoV-2 coronavirus covid-19 treatment"

In [22]:
query_vect = nlp(query).vector

In [23]:
#find 10 most similar abstracts as the above query
similar_abstracts = nn.kneighbors([query_vect])[1]

In [24]:
for abstract in similar_abstracts:
    print(df3['abstract'].iloc[abstract])

19051    The recent outbreak of respiratory illness in ...
36904    Antiviral agents are urgently needed to fight ...
7684     Summary SARS coronavirus continues to cause sp...
37532    Human coronavirus (HCoV) strain 229E infection...
28684    Severe acute respiratory syndrome (SARS) is an...
8950     Abstract The activity of inosine-5′-monophosph...
43259    Abstract The currently circulating H3N2 and H1...
31893    Two coronaviruses causing severe respiratory d...
9110     Abstract Originally developed and commercializ...
7683     Summary Background The outbreak of severe acut...
4935     Abstract We report on chloroquine, a 4-amino-q...
30910    Ebola virus infection can cause severe hemorrh...
43637    Abstract Ferret and mink coronaviruses typical...
12869    Abstract The anti-RNA virus activity of polyox...
8887     Abstract A novel swine acute diarrhea syndrome...
42245    Human coronaviruses (CoVs) are enveloped virus...
15282    Abstract Objectives The identification and ana...
42780    Abstract Feline coronavirus infection is commo...
18811    Last decade witnessed the outbreak of many lif...
34889    Until recently, human coronaviruses (HCoVs), s...
5921     Abstract Since the emergence of the severe acu...
17487    Summary Nitazoxanide is a broad-spectrum antiv...
30643    The highly pathogenic severe acute respiratory...
43973    Abstract The coronavirus disease 19 (COVID-19)...
12317    Publisher Summary This chapter discusses the a...
Name: abstract, dtype: object

In [25]:
output = pd.DataFrame((df3['abstract'].iloc[abstract]))

In [26]:
pd.set_option('display.max_colwidth', 0)
output.head(25)
#Output of the top 25 abstracts matching the query with index numbers

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   abstract
19051  The recent outbreak of respiratory illness in Wuhan, China is caused by a novel coronavirus, named 2019-nCoV, which is genetically close to a bat-derived coronavirus. 2019-nCoV is categorized as beta genus coronavirus, same as the two other strains - severe acute respiratory syndrome coronavirus (SARS-CoV) and Middle East respiratory syndrome coronavirus (MERS-CoV). Antiviral drugs commonly used in clinical practice, including neuraminidase inhibitors (oseltamivir, paramivir, zanamivir, etc.), ganciclovir, acyclovir and ribavirin, are invalid for 2019-nCoV and not recommended. Drugs are possibly effective for 2019-nCoV include: remdesivir, lopinavir / ritonavir, lopinavir / ritonavir combined with interferon-β, convalescent plasma, and monoclonal antibodies. But the efficacy and safety of these drugs for 2019-nCoV pneumonia patients need to be assessed by further clinical trials.
36904  Antiviral agents are urgently needed to fight severe acute respiratory syndrome (SARS). We showed that niclosamide, an existing antihelminthic drug, was able to inhibit replication of a newly discovered coronavirus, SARS-CoV; viral antigen synthesis was totally abolished at a niclosamide concentration of 1.56 μM, as revealed by immunoblot analysis. Thus, niclosamide represents a promising drug candidate for the effective treatment of SARS-CoV infection.
7684   Summary SARS coronavirus continues to cause sporadic cases of severe acute respiratory syndrome (SARS) in China. No active or passive immunoprophylaxis for disease induced by SARS coronavirus is available. We investigated prophylaxis of SARS coronavirus infection with a neutralising human monoclonal antibody in ferrets, which can be readily infected with the virus. Prophylactic administration of the monoclonal antibody at 10 mg/kg reduced replication of SARS coronavirus in the lungs of infected ferrets by 3·3 logs (95% Cl 2·6–4·0 logs; p<0·001), completely prevented the development of SARS coronavirus-induced macroscopic lung pathology (p=0·013), and abolished shedding of virus in pharyngeal secretions. The data generated in this animal model show that administration of a human monoclonal antibody might offer a feasible and effective prophylaxis for the control of human SARS coronavirus infection.
37532  Human coronavirus (HCoV) strain 229E infection, but not HCoV strain OC43 infection, of monocytes/macrophages from healthy donors and patients with multiple sclerosis in remission resulted in increased apoptosis, as measured by DNA changes and annexin V staining. Apoptosis correlated with the differential release of infectious virus. HCoV strain 229E titers were 10(3.5) to 10(6) 50% tissue culture-infective doses (TCID(50))/ml, and HCoV strain OC43 titers were only 10(1.2) to 10(2.7) TCID(50)/ml.
28684  Severe acute respiratory syndrome (SARS) is an infectious disease caused by a newly identified human coronavirus (SARS-CoV). Currently, no effective drug exists to treat SARS-CoV infection. In this study, we investigated whether a panel of commercially available antiviral drugs exhibit in vitro anti–SARS-CoV activity. A drug-screening assay that scores for virus-induced cytopathic effects on cultured cells was used. Tested were 19 clinically approved compounds from several major antiviral pharmacologic classes: nucleoside analogs, interferons, protease inhibitors, reverse transcriptase inhibitors, and neuraminidase inhibitors. Complete inhibition of cytopathic effects of SARS-CoV in culture was observed for interferon subtypes, β-1b, α-n1, α-n3, and human leukocyte interferon α. These findings support clinical testing of approved interferons for the treatment of SARS.
8950   Abstract The activity of inosine-5′-monophosphate dehydrogenase (IMPDH) inhibitors, mizoribine and ribavirin, against severe acute respiratory syndrome (SARS)-associated coronavirus (SARS-CoV) was determined by plaque reduction and yield reduction assays. Mizoribine and ribavirin selectively inhibited replication of SARS-CoV. The 50% inhibitory concentration (IC50) of mizoribine for SARS-CoV Frankfurt-1 and SARS-CoV HKU39849, as determined by plaque reduction was 3.5μg/ml and 16μg/ml, respectively, and the IC50 of ribavirin for SARS-CoV Frankfurt-1 and SARS-CoV HKU39849 was 20μg/ml and 80μg/ml, while the 50% cytotoxic concentration of mizoribine and ribavirin for Vero E6 cells exceeded 200μg/ml. In a yield reduction assay, mizoribine (10μg/ml) and ribavirin (40μg/ml) inhibited the replication of SARS-CoV and reduced the infectious SARS-CoV titers to one-tenth or less. Mizoribine inhibited replication of SARS-CoV more strongly than ribavirin. However, neither drug could completely inhibit replication of SARS-CoV even at concentrations up to 100μg/ml.
43259  Abstract The currently circulating H3N2 and H1N1 subtypes of influenza A virus cause a transient, febrile upper respiratory illness in most adults and children (“seasonal influenza”), but infants, the elderly, immunodeficient and chronically ill persons may develop life-threatening primary viral pneumonia or complications such as bacterial pneumonia. By contrast, avian influenza viruses such as the H5N1 virus that recently emerged in Southeast Asia can cause severe disease when transferred from domestic poultry to previously healthy people (“avian influenza”). Most H5N1 patients present with fever, cough and shortness of breath that progress rapidly to adult respiratory distress syndrome. In seasonal influenza, viral replication remains confined to the respiratory tract, but limited studies indicate that H5N1 infections are characterized by systemic viral dissemination, high cytokine levels and multiorgan failure. Gastrointestinal infection and encephalitis also occur. The licensed anti-influenza drugs (the M2 ion channel blockers, amantadine and rimantadine, and the neuraminidase inhibitors, oseltamivir and zanamivir) are beneficial for uncomplicated seasonal influenza, but appropriate dosing regimens for severe seasonal or H5N1 viral infections have not been defined. Treatment options may be limited by the rapid emergence of drug-resistant viruses. Ribavirin has also been used to a limited extent to treat influenza. This article reviews licensed drugs and treatments under development, including high-dose oseltamivir; parenterally administered neuraminidase inhibitors, peramivir and zanamivir; dimeric forms of zanamivir; the RNA polymerase inhibitor T-705; a ribavirin prodrug, viramidine; polyvalent and monoclonal antibodies; and combination therapies.
31893  Two coronaviruses causing severe respiratory disease and high mortality rates emerging within the past dozen years reinforces the need for clinically efficacious antivirals targeting coronaviruses. Alternative screening approaches for antivirals against the recently emergent Middle East respiratory syndrome coronavirus (MERS-CoV) may provide lead compounds to address this need. Two Antimicrobial Agents and Chemotherapy (AAC) papers screened libraries of approved compounds that may potentially be repurposed as MERS-CoV antivirals. A third AAC paper showed that a previously described severe acute respiratory syndrome coronavirus (SARS-CoV) helicase inhibitor also has activity against MERS-CoV.
9110   Abstract Originally developed and commercialized as an antiprotozoal agent, nitazoxanide was later identified as a first-in-class broad-spectrum antiviral drug and has been repurposed for the treatment of influenza. A Phase 2b/3 clinical trial recently published in The Lancet Infectious Diseases found that oral administration of nitazoxanide 600mg twice daily for five days reduced the duration of clinical symptoms and reduced viral shedding compared to placebo in persons with laboratory-confirmed influenza. The same study also suggested a potential benefit for subjects with influenza-like illness who did not have influenza or other documented respiratory viral infection. From a chemical perspective, nitazoxanide is the scaffold for a new class of drugs called thiazolides. These small-molecule drugs target host-regulated processes involved in viral replication. Nitazoxanide is orally bioavailable and safe with extensive post-marketing experience involving more than 75 million adults and children. A new dosage formulation of nitazoxanide is presently undergoing global Phase 3 clinical development for the treatment of influenza. Nitazoxanide inhibits a broad range of influenza A and B viruses including influenza A(pH1N1) and the avian A(H7N9) as well as viruses that are resistant to neuraminidase inhibitors. It is synergistic with neuraminidase inhibitors, and combination therapy with oseltamivir is being studied in humans as part of ongoing Phase 3 clinical development. Nitazoxanide also inhibits the replication of a broad range of other RNA and DNA viruses including respiratory syncytial virus, parainfluenza, coronavirus, rotavirus, norovirus, hepatitis B, hepatitis C, dengue, yellow fever, Japanese encephalitis virus and human immunodeficiency virus in cell culture assays. Clinical trials have indicated a potential role for thiazolides in treating rotavirus and norovirus gastroenteritis and chronic hepatitis B and chronic hepatitis C. Ongoing and future clinical development is focused on viral respiratory infections, viral gastroenteritis and emerging infections such as dengue fever.
7683   Summary Background The outbreak of severe acute respiratory syndrome (SARS) in 2002 was caused by a previously unknown coronavirus—SARS coronavirus (SARS-CoV). We have developed an experimental SARS vaccine for direct immunisation of the respiratory tract, the major site of SARS-coronavirus transmission and disease. Methods We expressed the complete SARS coronavirus envelope spike (S) protein from a recombinant attenuated parainfluenza virus (BHPIV3) that is being developed as a live attenuated, intranasal paediatric vaccine against human parainfluenza virus type 3 (HPIV3). We immunised eight African green monkeys, four with a single dose of BHPIV3/SARS-S and four with a control, BHPIV3/Ctrl, administered via the respiratory tract. A SARS-coronavirus challenge was given to all monkeys 28 days after immunisation. Findings Immunisation of animals with BHPIV3/SARS-S induced the production of SARS-coronavirus-neutralising serum antibodies, indicating that a systemic immune response resulted from mucosal immunisation. After challenge with SARS coronavirus, all monkeys in the control group shed SARS coronavirus, with shedding lasting 5–8 days. No viral shedding occurred in the group immunised with BHPIV3/SARS-S. Interpretation A vectored mucosal vaccine expressing the SARS-coronavirus S protein alone may be highly effective in a single-dose format for the prevention of SARS.
4935   Abstract We report on chloroquine, a 4-amino-quinoline, as an effective inhibitor of the replication of the severe acute respiratory syndrome coronavirus (SARS-CoV) in vitro. Chloroquine is a clinically approved drug effective against malaria. We tested chloroquine phosphate for its antiviral potential against SARS-CoV-induced cytopathicity in Vero E6 cell culture. Results indicate that the IC50 of chloroquine for antiviral activity (8.8±1.2μM) was significantly lower than its cytostatic activity; CC50 (261.3±14.5μM), yielding a selectivity index of 30. The IC50 of chloroquine for inhibition of SARS-CoV in vitro approximates the plasma concentrations of chloroquine reached during treatment of acute malaria. Addition of chloroquine to infected cultures could be delayed for up to 5h postinfection, without an important drop in antiviral activity. Chloroquine, an old antimalarial drug, may be considered for immediate use in the prevention and treatment of SARS-CoV infections.
30910  Ebola virus infection can cause severe hemorrhagic fever with a high mortality in humans. The outbreaks of Ebola viruses in 2014 represented the most serious Ebola epidemics in history and greatly threatened public health worldwide. The development of additional effective anti-Ebola therapeutic agents is therefore quite urgent. In this study, via high throughput screening of Food and Drug Administration-approved drugs, we identified that teicoplanin, a glycopeptide antibiotic, potently prevents the entry of Ebola envelope pseudotyped viruses into the cytoplasm. Furthermore, teicoplanin also has an inhibitory effect on transcription- and replication-competent virus-like particles, with an IC(50) as low as 330 nm. Comparative analysis further demonstrated that teicoplanin is able to block the entry of Middle East respiratory syndrome (MERS) and severe acute respiratory syndrome (SARS) envelope pseudotyped viruses as well. Teicoplanin derivatives such as dalbavancin, oritavancin, and telavancin can also inhibit the entry of Ebola, MERS, and SARS viruses. Mechanistic studies showed that teicoplanin blocks Ebola virus entry by specifically inhibiting the activity of cathepsin L, opening a novel avenue for the development of additional glycopeptides as potential inhibitors of cathepsin L-dependent viruses. Notably, given that teicoplanin has routinely been used in the clinic with low toxicity, our work provides a promising prospect for the prophylaxis and treatment of Ebola, MERS, and SARS virus infection.
43637  Abstract Ferret and mink coronaviruses typically cause catarrhal diarrhea in ferrets and minks, respectively. In recent years, however, systemic fatal coronavirus infection has emerged in ferrets, which resembles feline infectious peritonitis (FIP) in cats. FIP is a highly fatal systemic disease caused by a virulent feline coronavirus infection in cats. Despite the importance of coronavirus infections in these animals, there are no effective commercial vaccines or antiviral drugs available for these infections. We have previously reported the efficacy of a protease inhibitor in cats with FIP, demonstrating that a virally encoded 3C-like protease (3CLpro) is a valid target for antiviral drug development for coronavirus infections. In this study, we extended our previous work on coronavirus inhibitors and investigated the structure-activity relationships of a focused library of protease inhibitors for ferret and mink 3CLpro. Using the fluorescence resonance energy transfer assay, we identified potent inhibitors broadly effective against feline, ferret and mink coronavirus 3CLpro. Multiple amino acid sequence analysis and modelling of 3CLpro of ferret and mink coronaviruses were conducted to probe the structural basis for these findings. The results of this study provide support for further research to develop broad-spectrum antiviral agents for multiple coronavirus infections. To the best of our knowledge, this is the first report on small molecule inhibitors of ferret and mink coronaviruses.
12869  Abstract The anti-RNA virus activity of polyoxometalates (POM) is reviewed, with a special emphasis on the anti-respiratory virus activities. There are many causative agents of acute viral respiratory infections; and it is rather difficult to identify the relevant agent in a given case by rapid clinical means. During acute progress of infection before the definitive diagnosis is obtained physicians need to prescribe certain broad spectrum anti-viral drugs. A titanium containing polyoxotungstate, PM-523 exhibited potent anti-influenza virus (FluV) A and anti-respiratory syncytial virus (RSV) activities in vitro. Therapeutic effect of FluV A infected mice with aerosol inhalation of PM-523 was proven. A vanadium substituted polyoxotungstate, PM-1001 has antiviral activity against FluV A, RSV, parainfluenza virus (PfluV) type 2, Dengue fiver virus, HIV-1 and SARS coronavirus in vitro. Thus, POMs have been proven to be broad spectrum and non-toxic anti-RNA virus agents in both in vitro and in vivo experiments and are promising candidates for first-line therapeutics in acute respiratory diseases.
8887   Abstract A novel swine acute diarrhea syndrome Coronavirus (SADS-CoV) that causes severe diarrhea in suckling piglets was identified in southern China in 2017. A simple and rapid detection test was developed for this virus using real-time RT-LAMP based on the conserved N gene of the virus. The method had a detection limit of 1.0 × 101 copies/μL with no cross-reactions with classical swine fever virus, porcine and respiratory syndrome virus NA, porcine and respiratory syndrome virus EU, transmissible gastroenteritis coronavirus, foot and mouth disease virus, porcine epidemic diarrhea virus (S-INDEL and non-S-INDEL), swine influenza virus subtype H1N1, porcine circovirus type 2, seneca valley virus, porcine parvovirus, porcine deltacoronavirus and rotavirus. This method was also reproducible. Twenty of 24 clinical samples were identified as SADS-CoV RNA-positive by the real-time RT-LAMP and the results were consistent with that of the real time RT-PCR method. This new method for detecting SADS-CoV is specific and sensitive for the detection of SADS-CoV.

In [27]:
#From the above abstracts, abstracts 28684, 8950, 7683 appear relevant to our search for newer treatments.
#Abstract 4935 and 34889 is relevant to chloroquine in treating covid-19. 
#Abstract 18811 is relevant to a monoclonal antibody treatment against covid-19.
#Abstract 30643 is relevant to a new target Abelson tyrosine-protein kinase 2 (Abl2) against covid-19.
#Abstract 43973 is important in discussing various approaches towards developing a vaccine and treatments against covid-19.

In [28]:
#Next step will be to inspect the detailed papers for these abstracts.
#Let us inspect the abstracts first and raw some conclusions.

In [29]:
#pd.set_option('display.max_colwidth', 0)
query1 = output.iloc[ 10, : ]
query1.head()

abstract    Abstract We report on chloroquine, a 4-amino-quinoline, as an effective inhibitor of the replication of the severe acute respiratory syndrome coronavirus (SARS-CoV) in vitro. Chloroquine is a clinically approved drug effective against malaria. We tested chloroquine phosphate for its antiviral potential against SARS-CoV-induced cytopathicity in Vero E6 cell culture. Results indicate that the IC50 of chloroquine for antiviral activity (8.8±1.2μM) was significantly lower than its cytostatic activity; CC50 (261.3±14.5μM), yielding a selectivity index of 30. The IC50 of chloroquine for inhibition of SARS-CoV in vitro approximates the plasma concentrations of chloroquine reached during treatment of acute malaria. Addition of chloroquine to infected cultures could be delayed for up to 5h postinfection, without an important drop in antiviral activity. Chloroquine, an old antimalarial drug, may be considered for immediate use in the prevention and treatment of SARS-CoV infections.
Name: 4935, dtype: object

Abstract 4935: Abstract We report on chloroquine, a 4-amino-quinoline, as an effective inhibitor of the replication of the severe acute respiratory syndrome coronavirus (SARS-CoV) in vitro. Chloroquine is a clinically approved drug effective against malaria. We tested chloroquine phosphate for its antiviral potential against SARS-CoV-induced cytopathicity in Vero E6 cell culture. Results indicate that the IC50 of chloroquine for antiviral activity (8.8±1.2μM) was significantly lower than its cytostatic activity; CC50 (261.3±14.5μM), yielding a selectivity index of 30. The IC50 of chloroquine for inhibition of SARS-CoV in vitro approximates the plasma concentrations of chloroquine reached during treatment of acute malaria. Addition of chloroquine to infected cultures could be delayed for up to 5h postinfection, without an important drop in antiviral activity. Chloroquine, an old antimalarial drug, may be considered for immediate use in the prevention and treatment of SARS-CoV infections.

Abstract 4935 key takeway:
Chloroquine reduced the antiviral activity of SARS-COV (2003 SARS outbreak) in in vitro study and could be an effective treatment for this infection.

In [30]:
query2 = output.iloc[ 19, : ]
query2.head()

abstract    Until recently, human coronaviruses (HCoVs), such as HCoV strain OC43 (HCoV-OC43), were mainly known to cause 15 to 30% of mild upper respiratory tract infections. In recent years, the identification of new HCoVs, including severe acute respiratory syndrome coronavirus, revealed that HCoVs can be highly pathogenic and can cause more severe upper and lower respiratory tract infections, including bronchiolitis and pneumonia. To date, no specific antiviral drugs to prevent or treat HCoV infections are available. We demonstrate that chloroquine, a widely used drug with well-known antimalarial effects, inhibits HCoV-OC43 replication in HRT-18 cells, with a 50% effective concentration (± standard deviation) of 0.306 ± 0.0091 μM and a 50% cytotoxic concentration (± standard deviation) of 419 ± 192.5 μM, resulting in a selectivity index of 1,369. Further, we investigated whether chloroquine could prevent HCoV-OC43-induced death in newborn mice. Our results show that a lethal HCoV-OC43 infection in newborn C57BL/6 mice can be treated with chloroquine acquired transplacentally or via maternal milk. The highest survival rate (98.6%) of the pups was found when mother mice were treated daily with a concentration of 15 mg of chloroquine per kg of body weight. Survival rates declined in a dose-dependent manner, with 88% survival when treated with 5 mg/kg chloroquine and 13% survival when treated with 1 mg/kg chloroquine. Our results show that chloroquine can be highly effective against HCoV-OC43 infection in newborn mice and may be considered as a future drug against HCoVs.
Name: 34889, dtype: object

Abstract 34889: Until recently, human coronaviruses (HCoVs), such as HCoV strain OC43 (HCoV-OC43), were mainly known to cause 15 to 30% of mild upper respiratory tract infections. In recent years, the identification of new HCoVs, including severe acute respiratory syndrome coronavirus, revealed that HCoVs can be highly pathogenic and can cause more severe upper and lower respiratory tract infections, including bronchiolitis and pneumonia. To date, no specific antiviral drugs to prevent or treat HCoV infections are available. We demonstrate that chloroquine, a widely used drug with well-known antimalarial effects, inhibits HCoV-OC43 replication in HRT-18 cells, with a 50% effective concentration (± standard deviation) of 0.306 ± 0.0091 μM and a 50% cytotoxic concentration (± standard deviation) of 419 ± 192.5 μM, resulting in a selectivity index of 1,369. Further, we investigated whether chloroquine could prevent HCoV-OC43-induced death in newborn mice. Our results show that a lethal HCoV-OC43 infection in newborn C57BL/6 mice can be treated with chloroquine acquired transplacentally or via maternal milk. The highest survival rate (98.6%) of the pups was found when mother mice were treated daily with a concentration of 15 mg of chloroquine per kg of body weight. Survival rates declined in a dose-dependent manner, with 88% survival when treated with 5 mg/kg chloroquine and 13% survival when treated with 1 mg/kg chloroquine. Our results show that chloroquine can be highly effective against HCoV-OC43 infection in newborn mice and may be considered as a future drug against HCoVs.

Note: HCoV strain OC43 (HCoV-OC43) is a different strain than COVID-19 (SARS-COV) but chloroquine seems to have a class effect against coronaviruses.

****Abstract 43973 is an important review of vaccine and treatment approaches against COVID-19.

In [31]:
#The full text for this abstract can be accessed here : https://github.com/bs3537/DS-Unit-4-Sprint-1-NLP/blob/master/1-s2.0-S2090123220300540-main.pdf

In [32]:
#NLP Topic Modeling for the selected abstract above

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vect = TfidfVectorizer(stop_words='english', tokenizer = tokenize, ngram_range=(1,2))

In [35]:
tf = vect.fit_transform(output['abstract'])

/opt/conda/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['nt'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

In [36]:
from sklearn.decomposition import LatentDirichletAllocation

In [37]:
lda = LatentDirichletAllocation(n_components=50, random_state=0, n_jobs=-1)

In [38]:
lda.fit(tf)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=50, n_jobs=-1,
                          perp_tol=0.1, random_state=0, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [39]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "\nTopic #%d: " % topic_idx
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()

In [40]:
tfidf_feature_names = vect.get_feature_names()
top_words = print_top_words(lda, tfidf_feature_names, 25)
top_words

Topic #0: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #1: influenza h5n1 seasonal seasonal influenza zanamivir limited avian influenza avian licensed oseltamivir pneumonia amantadine rimantadine amantadine viral pneumonia inhibitors peramivir viral infections circulating h3n2 remains confined peramivir ribavirin prodrug forms viral dissemination forms zanamivir disease transferred confined respiratory

Topic #2: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #3: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #4: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #5: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #6: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #7: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #8: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #9: chloroquine hcov hcov strain strain mers-cov patients sars-cov mers-cov strain oc43 229e oc43 suspected apoptosis strain 229e highly pathogenic activity spreading titers pathogenic vitro results cases malaria sars-cov vitro ic50 chloroquine influenza virus

Topic #10: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #11: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #12: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #13: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #14: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #15: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #16: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #17: mg/kg chloroquine infections available survival rate treated 5 upper lower deviation 419 known cause results lethal bronchiolitis pneumonia declined mother chloroquine acquired coronaviruses hcovs date bronchiolitis highest inhibits upper respiratory drugs approved duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested

Topic #18: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #19: sars sars coronavirus human immunisation covs production monoclonal antibody antibody shedding protein sars-coronavirus monkeys bhpiv3/sars-s respiratory tract tract administration control suppresses monoclonal coronavirus summary mg/kg human monoclonal logs days

Topic #20: clinical mers-cov syndrome coronavirus 2019-ncov east middle middle east east respiratory including agents coronavirus mers-cov infections antivirals need vitro mice hcov-oc43 outbreak china fluv broad survival treated ± hcovs

Topic #21: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #22: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #23: sars niclosamide porcine virus sads-cov method sars-cov 3clpro rtv lpv 3clpro virus porcine swine diarrhea detection proteinase hydrogen bonds sars lpv sars rtv hydrogen free proteinase inhibitors bonds molecular sars virus fight severe

Topic #24: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #25: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #26: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #27: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #28: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #29: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #30: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #31: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #32: coronavirus respiratory sars-cov viral inhibitors syndrome respiratory syndrome infection severe virus antiviral acute drugs coronaviruses viruses drug protease replication acute respiratory severe acute effective feline treatment human covid-19

Topic #33: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #34: patients active hiv hepatitis viruses analogue reverse analogue drug active nucleoside analogue cytomegalovirus abacavir hepatitis reverse reverse transcriptase transcriptase inhibitors transcriptase nucleoside associated valaciclovir antigen (hbeag)negative highest minimum complex taking herpesviruses abacavir placebo herpesviruses hepatitis taking

Topic #35: ribavirin mizoribine ferret mink mink ferret monoclonal monoclonal antibodies reduction replication sars-cov antibodies novel coronavirus develop concentration inhibited inhibited replication sars-cov 3clpro novel prevent mizoribine ribavirin infections 50 research mink coronaviruses coronavirus infections

Topic #36: nitazoxanide influenza clinical development hepatitis treatment influenza phase b potential phase 3 broad range 3 clinical norovirus thiazolides nitazoxanide inhibits rotavirus norovirus viruses including hepatitis b chronic hepatitis chronic rotavirus ongoing gastroenteritis inhibits range 3

Topic #37: nitazoxanide trials cytokines inhibiting expression potential mers-cov summary nitazoxanide interleukin interleukin 6 extensively clinical include vitro models protein nitazoxanide including dose-ranging n protein expression viral expression candidate treatment trials including pro-inflammatory mechanism trials evaluation research include production pro-inflammatory future research antiviral agent

Topic #38: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #39: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #40: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #41: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #42: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #43: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #44: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #45: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #46: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #47: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #48: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

Topic #49: ≥37.5 ° drugs streamlines e6 cell e6 dynamics simulations dynamics duration clinical duration drugs treatments drugs treatment drugs titanium drugs tested drugs target drugs prevent drugs active drugs possibly drugs m2 drugs inhibitors drugs identified drugs exhibit drugs evaluated drugs cytomegalovirus drugs commonly drugs characterized drugs called

In [41]:
!pip install pyLDAvis

Requirement already satisfied: pyLDAvis in /opt/conda/lib/python3.6/site-packages (2.1.2)
Requirement already satisfied: scipy>=0.18.0 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (1.4.1)
Requirement already satisfied: joblib>=0.8.4 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (0.14.1)
Requirement already satisfied: future in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (0.18.2)
Requirement already satisfied: pandas>=0.17.0 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (0.25.3)
Requirement already satisfied: pytest in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (5.0.1)
Requirement already satisfied: numexpr in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (2.6.9)
Requirement already satisfied: funcy in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (1.14)
Requirement already satisfied: numpy>=1.9.2 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (1.18.1)
Requirement already satisfied: jinja2>=2.7.2 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (2.11.1)
Requirement already satisfied: wheel>=0.23.0 in /opt/conda/lib/python3.6/site-packages (from pyLDAvis) (0.34.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/conda/lib/python3.6/site-packages (from pandas>=0.17.0->pyLDAvis) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.6/site-packages (from pandas>=0.17.0->pyLDAvis) (2019.3)
Requirement already satisfied: py>=1.5.0 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (1.8.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (20.1)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (8.2.0)
Requirement already satisfied: atomicwrites>=1.0 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (1.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (0.13.1)
Requirement already satisfied: importlib-metadata>=0.12 in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (1.5.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.6/site-packages (from pytest->pyLDAvis) (0.1.8)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.6/site-packages (from jinja2>=2.7.2->pyLDAvis) (1.1.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas>=0.17.0->pyLDAvis) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from packaging->pytest->pyLDAvis) (2.4.6)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.6/site-packages (from importlib-metadata>=0.12->pytest->pyLDAvis) (2.2.0)

In [42]:
import pyLDAvis.gensim

pyLDAvis.enable_notebook()

In [43]:
data = output['abstract'].apply(tokenize)

In [44]:
id2word = corpora.Dictionary(data)

In [45]:
corpus = [id2word.doc2bow(token) for token in data]

In [46]:
lda2 = LdaMulticore(corpus = corpus,
                   id2word = id2word,
                   random_state = 42,
                   num_topics = 15,
                   passes = 10,
                   workers = 4)

In [47]:
lda2.print_topics()

[(0,
  '0.022*"patients" + 0.017*"active" + 0.017*"viruses" + 0.017*"inhibitors" + 0.017*"drug" + 0.011*"associated" + 0.011*"transcriptase" + 0.011*"analogue" + 0.011*"HIV" + 0.011*"reverse"'),
 (1,
  '0.029*"influenza" + 0.017*"H5N1" + 0.017*"seasonal" + 0.017*"viral" + 0.013*"respiratory" + 0.013*"zanamivir" + 0.013*"limited" + 0.009*"virus" + 0.009*"cause" + 0.009*"infections"'),
 (2,
  '0.001*"viral" + 0.001*"clinical" + 0.001*"human" + 0.001*"respiratory" + 0.001*"COVID-19" + 0.001*"coronavirus" + 0.001*"nitazoxanide" + 0.001*"influenza" + 0.001*"virus" + 0.001*"viruses"'),
 (3,
  '0.036*"protease" + 0.031*"feline" + 0.018*"viral" + 0.018*"inhibitors" + 0.018*"coronavirus" + 0.018*"3CL" + 0.014*"replication" + 0.014*"infectious" + 0.014*"FIP" + 0.014*"coronaviruses"'),
 (4,
  '0.032*"2019-nCoV" + 0.032*"coronavirus" + 0.019*"respiratory" + 0.013*"lopinavir" + 0.013*"ritonavir" + 0.013*"clinical" + 0.013*"drugs" + 0.013*"syndrome" + 0.007*"zanamivir" + 0.007*"oseltamivir"'),
 (5,
  '0.022*"virus" + 0.020*"clinical" + 0.018*"respiratory" + 0.018*"viral" + 0.016*"influenza" + 0.013*"Nitazoxanide" + 0.011*"vitro" + 0.011*"nitazoxanide" + 0.009*"treatment" + 0.009*"trials"'),
 (6,
  '0.019*"chloroquine" + 0.019*"Ebola" + 0.014*"teicoplanin" + 0.014*"respiratory" + 0.014*"viruses" + 0.011*"HCoV-OC43" + 0.011*"treated" + 0.011*"±" + 0.011*"mice" + 0.011*"HCoVs"'),
 (7,
  '0.049*"SARS" + 0.035*"coronavirus" + 0.014*"virus" + 0.014*"respiratory" + 0.014*"human" + 0.011*"monoclonal" + 0.011*"vaccine" + 0.011*"antibody" + 0.011*"SARS-coronavirus" + 0.011*"shedding"'),
 (8,
  '0.038*"virus" + 0.020*"SARS" + 0.013*"porcine" + 0.011*"patients" + 0.011*"coronavirus" + 0.011*"syndrome" + 0.009*"influenza" + 0.009*"respiratory" + 0.009*"HCoV" + 0.009*"strain"'),
 (9,
  '0.001*"respiratory" + 0.001*"protease" + 0.001*"viral" + 0.001*"feline" + 0.001*"chloroquine" + 0.001*"mice" + 0.001*"coronaviruses" + 0.001*"coronavirus" + 0.001*"infection" + 0.001*"Nitazoxanide"'),
 (10,
  '0.001*"virus" + 0.001*"porcine" + 0.001*"swine" + 0.001*"method" + 0.001*"SADS-CoV" + 0.001*"coronavirus" + 0.001*"respiratory" + 0.001*"detection" + 0.001*"diarrhea" + 0.001*"protease"'),
 (11,
  '0.001*"coronavirus" + 0.001*"protease" + 0.001*"feline" + 0.001*"inhibitors" + 0.001*"coronaviruses" + 0.001*"FIP" + 0.001*"infections" + 0.001*"cats" + 0.001*"ferret" + 0.001*"mink"'),
 (12,
  '0.035*"SARS-CoV" + 0.027*"coronavirus" + 0.019*"respiratory" + 0.017*"MERS-CoV" + 0.015*"syndrome" + 0.011*"acute" + 0.011*"severe" + 0.010*"infection" + 0.009*"replication" + 0.009*"human"'),
 (13,
  '0.033*"coronavirus" + 0.020*"mink" + 0.018*"coronaviruses" + 0.016*"infections" + 0.016*"inhibitors" + 0.016*"3CLpro" + 0.016*"ferret" + 0.012*"antiviral" + 0.012*"cats" + 0.012*"FIP"'),
 (14,
  '0.002*"MERS-CoV" + 0.001*"2003" + 0.001*"spreading" + 0.001*"imatinib" + 0.001*"coronavirus" + 0.001*"kinase" + 0.001*"fatality" + 0.001*"cases" + 0.001*"drugs" + 0.001*"required"')]

In [48]:
import re
words = [re.findall(r'"([^"]*)"',t[1]) for t in lda2.print_topics()]

In [49]:
topics = [' '.join(t[0:10]) for t in words]

In [50]:
for id, t in enumerate(topics): 
    print(f"------ Topic {id} ------")
    print(t, end="\n\n")

------ Topic 0 ------
patients active viruses inhibitors drug associated transcriptase analogue HIV reverse

------ Topic 1 ------
influenza H5N1 seasonal viral respiratory zanamivir limited virus cause infections

------ Topic 2 ------
viral clinical human respiratory COVID-19 coronavirus nitazoxanide influenza virus viruses

------ Topic 3 ------
protease feline viral inhibitors coronavirus 3CL replication infectious FIP coronaviruses

------ Topic 4 ------
2019-nCoV coronavirus respiratory lopinavir ritonavir clinical drugs syndrome zanamivir oseltamivir

------ Topic 5 ------
virus clinical respiratory viral influenza Nitazoxanide vitro nitazoxanide treatment trials

------ Topic 6 ------
chloroquine Ebola teicoplanin respiratory viruses HCoV-OC43 treated ± mice HCoVs

------ Topic 7 ------
SARS coronavirus virus respiratory human monoclonal vaccine antibody SARS-coronavirus shedding

------ Topic 8 ------
virus SARS porcine patients coronavirus syndrome influenza respiratory HCoV strain

------ Topic 9 ------
respiratory protease viral feline chloroquine mice coronaviruses coronavirus infection Nitazoxanide

------ Topic 10 ------
virus porcine swine method SADS-CoV coronavirus respiratory detection diarrhea protease

------ Topic 11 ------
coronavirus protease feline inhibitors coronaviruses FIP infections cats ferret mink

------ Topic 12 ------
SARS-CoV coronavirus respiratory MERS-CoV syndrome acute severe infection replication human

------ Topic 13 ------
coronavirus mink coronaviruses infections inhibitors 3CLpro ferret antiviral cats FIP

------ Topic 14 ------
MERS-CoV 2003 spreading imatinib coronavirus kinase fatality cases drugs required

In [51]:
pyLDAvis.gensim.prepare(lda2, corpus, id2word)

/opt/conda/lib/python3.6/site-packages/pyLDAvis/_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
12     0.002089 -0.169397  1       1        31.966305
5     -0.083668  0.044363  2       1        13.364851
8     -0.154904  0.061777  3       1        13.149855
6     -0.035466 -0.134638  4       1        10.379828
7     -0.077758 -0.066080  5       1        7.467419
13     0.152519 -0.025888  6       1        6.006211
1     -0.015423  0.074886  7       1        5.776896
3      0.148581  0.014715  8       1        5.201589
0      0.051762  0.117390  9       1        3.655487
4     -0.024236  0.001355  10      1        2.735028
14     0.007099  0.013416  11      1        0.059306
11     0.008241  0.016625  12      1        0.059306
10     0.006926  0.017440  13      1        0.059306
9      0.007346  0.016835  14      1        0.059306
2      0.006892  0.017201  15      1        0.059306 , topic_info=    Category       Freq            Term      Total  loglift  logprob
22   Default  49.000000  coronavirus     49.000000  30.0000  30.0000
63   Default  25.000000  SARS            25.000000  29.0000  29.0000
7    Default  34.000000  SARS-CoV        34.000000  28.0000  28.0000
322  Default  14.000000  influenza       14.000000  27.0000  27.0000
142  Default  32.000000  virus           32.000000  26.0000  26.0000
..       ...        ...    ...                 ...      ...      ...
419  Topic15  0.001388   broad-spectrum  4.350501  -0.6198  -7.0801
5    Topic15  0.001386   MERS-CoV        21.316536 -2.2108  -7.0819
60   Topic15  0.001386   trials          5.164648  -0.7932  -7.0819
403  Topic15  0.001385   C               2.927794  -0.2264  -7.0827
89   Topic15  0.001384   treatment       11.558467 -1.5997  -7.0828

[1008 rows x 6 columns], token_table=      Topic      Freq       Term
term
979   4      0.792693  0.0091
980   4      0.792762  0.306
750   3      0.773349  101
982   4      0.978604  15
179   1      0.869469  19
...  ..           ...  ..
61    10     0.336022  zanamivir
1021  4      0.831449  ±
800   3      0.773347  ×
92    1      0.338478  μM
92    4      0.676956  μM

[878 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[13, 6, 9, 7, 8, 14, 2, 4, 1, 5, 15, 12, 11, 10, 3])

In [52]:
#On hovering over 2019-nCoV, this word is most commonly present in topics 1 and 10. 
#COVID-19 word is most commonly present in topic 1.